# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digital_signature.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(497, 461)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 331, 71))
        self.textEdit.setObjectName("textEdit")
        self.signature = QtWidgets.QPushButton(Dialog)
        self.signature.setGeometry(QtCore.QRect(72, 360, 151, 51))
        self.signature.setObjectName("signature")
        self.verify = QtWidgets.QPushButton(Dialog)
        self.verify.setGeometry(QtCore.QRect(280, 360, 141, 51))
        self.verify.setObjectName("verify")
        self.Choose_File = QtWidgets.QPushButton(Dialog)
        self.Choose_File.setGeometry(QtCore.QRect(390, 50, 93, 28))
        self.Choose_File.setObjectName("Choose_File")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 130, 331, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 230, 331, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.choose_private_key_btn = QtWidgets.QPushButton(Dialog)
        self.choose_private_key_btn.setGeometry(QtCore.QRect(390, 150, 93, 28))
        self.choose_private_key_btn.setObjectName("choose_private_key_btn")
        self.choose_public_key_btn = QtWidgets.QPushButton(Dialog)
        self.choose_public_key_btn.setGeometry(QtCore.QRect(390, 250, 93, 28))
        self.choose_public_key_btn.setObjectName("choose_public_key_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.signature.setText(_translate("Dialog", "签名"))
        self.verify.setText(_translate("Dialog", "验证签名"))
        self.Choose_File.setText(_translate("Dialog", "选择文件"))
        self.choose_private_key_btn.setText(_translate("Dialog", "选择私钥"))
        self.choose_public_key_btn.setText(_translate("Dialog", "选择公钥"))
