# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Encrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(742, 366)
        self.Choose_File = QtWidgets.QPushButton(Dialog)
        self.Choose_File.setGeometry(QtCore.QRect(560, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Choose_File.setFont(font)
        self.Choose_File.setAutoDefault(True)
        self.Choose_File.setFlat(False)
        self.Choose_File.setObjectName("Choose_File")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.FileEdit = QtWidgets.QTextEdit(Dialog)
        self.FileEdit.setGeometry(QtCore.QRect(120, 220, 421, 91))
        self.FileEdit.setObjectName("FileEdit")
        self.En_file = QtWidgets.QPushButton(Dialog)
        self.En_file.setGeometry(QtCore.QRect(560, 270, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.En_file.setFont(font)
        self.En_file.setObjectName("En_file")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.KeyEdit = QtWidgets.QTextEdit(Dialog)
        self.KeyEdit.setGeometry(QtCore.QRect(120, 70, 421, 91))
        self.KeyEdit.setObjectName("KeyEdit")
        self.Choose_keyFile = QtWidgets.QPushButton(Dialog)
        self.Choose_keyFile.setGeometry(QtCore.QRect(560, 80, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Choose_keyFile.setFont(font)
        self.Choose_keyFile.setAutoDefault(True)
        self.Choose_keyFile.setFlat(False)
        self.Choose_keyFile.setObjectName("Choose_keyFile")
        self.En_key = QtWidgets.QPushButton(Dialog)
        self.En_key.setGeometry(QtCore.QRect(560, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.En_key.setFont(font)
        self.En_key.setObjectName("En_key")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "文件/密钥加密"))
        self.Choose_File.setText(_translate("Dialog", "浏览"))
        self.label_4.setText(_translate("Dialog", "选择要加密的文件"))
        self.En_file.setText(_translate("Dialog", "确认加密"))
        self.label_5.setText(_translate("Dialog", "选择要加密的密钥"))
        self.Choose_keyFile.setText(_translate("Dialog", "浏览"))
        self.En_key.setText(_translate("Dialog", "确认加密"))
