# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Key_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(343, 120)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Create_randomAES_key = QtWidgets.QToolButton(Dialog)
        self.Create_randomAES_key.setGeometry(QtCore.QRect(170, 30, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Create_randomAES_key.setFont(font)
        self.Create_randomAES_key.setObjectName("Create_randomAES_key")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Create_RSA_key = QtWidgets.QToolButton(Dialog)
        self.Create_RSA_key.setGeometry(QtCore.QRect(170, 70, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.Create_RSA_key.setFont(font)
        self.Create_RSA_key.setObjectName("Create_RSA_key")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "密钥生成"))
        self.label_2.setText(_translate("Dialog", "AES随机密钥"))
        self.Create_randomAES_key.setText(_translate("Dialog", "生成"))
        self.label_3.setText(_translate("Dialog", "RSA密钥对"))
        self.Create_RSA_key.setText(_translate("Dialog", "生成"))
